= Python Flask Application to query Neo4j Database

First get yourself setup with link:http://docs.python-guide.org/en/latest/dev/virtualenvs/[Virtual Env] so we don't break any other Python stuff you have on your machine. After you've got that installed let's setup an environment for our app:

[source]
----
$ virtualenv cypher-app
New python executable in cypher-app/bin/python
Installing setuptools, pip...done.
----

[source]
----
$ source cypher-app/bin/activate
----

The next step is to install the dependencies for the app:

[source]
----
(cypher-app)$ pip install -r requirements.txt
...
Successfully installed py2neo
Cleaning up...
----

And finally let's start up a Bottle web server:

[source]
----
(cypher-app)$ python example.py
Bottle v0.12.7 server starting up (using WSGIRefServer())...
Listening on http://127.0.0.1:8080/
Hit Ctrl-C to quit.
----

Navigate to http://localhost:8080 and you should see your first Neo4j application

# Cypher Queries
- The Following Cypher query is used to get the total count of all the edges connecting nodes with label N.
```
cypher> MATCH (n:<N>)-[r]->(m:<N>) RETURN COUNT(r)
```
- The Following Cypher query is used to get the total number of networks existing in the backend. 
```
cypher> MATCH (n)-[r]->() RETURN COUNT(r)
```
- The following Cypher query is used to upload edges to Neo4j Backend. 
```
cypher> USING PERIODIC COMMIT LOAD CSV FROM <Link to the csv file containing the four fields node1, node2, edge_attribute1, edge attribute2> AS line FIELDTERMINATOR <>  MATCH(u:ShootOsmoGene{name:line[0] }), (r:<NodeLabel>{name:line[1]}) CREATE (u)-[:CONNECTED_TO{correlation_coefficient:line[3], hrr_rank:line[2]}]->(r);
```

- The following Cypher query helps to get all the nodes related to gene x
```
cypher> MATCH (b) - [r] - (:<Node Label> {name: x})
cypher> RETURN b
```
- The following Cypher query helps to get all relations related to gene x
```
cypher> MATCH (b) - [r] - (:<Node Label> {name: x})
cypher> RETURN r
```
